# Generated by Django 3.0.2 on 2020-01-07 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20191219_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='subsubcategory', to='item.SubSubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 13, 33, 25, 417436, tzinfo=utc), verbose_name='Срок действия безлимитного кода'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Category', verbose_name='Основная категория'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.SubCategory', verbose_name='Основная подкатегория'),
        ),
    ]
